### ISSUE TITLE
Modules turn on/off on realms on its own

### ISSUE THREAD

**Issue by Dylanomeneer** [Visual1mpact/Paradox_AntiCheat#22]
When everyone is logged off the Minecraft Realm all the modules that we're turned off gets turned on again

Is there a fix to this?

**Comment by Dylanomeneer** [comment]
This is in1.18.30 and 1.18.31

**Comment by SortingFarmer** [comment]
Well there is a fix, you just simply go to in the world files of the anticheat scripts - data - config.js and there you can change all settings you need and when you leve and then join it will stay that way

**Comment by Dylanomeneer** [comment]
So i did that even went so far to delete the .js files of the original modules but it still is doing it, i updated everything correctly

I'm talking about these modules:

xraya
illegalitemsb
illegalitemsc
jesusa
spammera
spammerb
spammerc
spammersd
antispam
flya
antinukera

They either spam my or everyone chat or just bug out: example the "flya" module activates when someone is falling and then they get teleported to a random player in the world

**Comment by Visual1mpact** [comment]
The file, config.js, is the configuration file for Paradox. It's intended for people to modify the contents inside it. You should not delete it at all. Paradox uses that file to determine the default settings. So if there are commands you wish to disable and not allow then you can change those custom commands from true to false and they will show on your help menu as being disabled. If you wanted to disable any Modules because you don't want to use them then you could scroll down the file and find the module then change it from true to false. Then save your edited changes and load Paradox into your world. Those changes will be the default settings Paradox uses when you restart your world. The settings you set in the game itself does not persist after a restart except for a very tiny portion. The project uses the configuration file to determine those settings.

**Comment by Dylanomeneer** [comment]
Thank you but i meant i deleted the files such as: flya.js not the config.js and i did that before but i have might messed something up while doing it so it should be fixed, if it isn't i will send a follow up message

**Comment by Visual1mpact** [comment]
Also, which version of Paradox are you using?

**Comment by Visual1mpact** [comment]
> Thank you but i meant i deleted the files such as: flya.js not the config.js and i did that before but i have might messed something up while doing it so it should be fixed, if it isn't i will send a follow up message

Don't delete those files. You will have Paradox bug out if you do that.

**Comment by Dylanomeneer** [comment]
2.10.34

**Comment by Visual1mpact** [comment]
> 2.10.34

Oh wow, ok so you are using an older version. I would recommend updating when you get the chance. A lot of bug fixes has been implemented since then. Will be another release in the next day or so if all goes well.

**Comment by Dylanomeneer** [comment]
So i did update it but i just turned on allowgmc (so it's on ENABLED) and everyone who isn't op gets put in creative

**Comment by Visual1mpact** [comment]
> So i did update it but i just turned on allowgmc (so it's on ENABLED) and everyone who isn't op gets put in creative

Just tested this and you are right. This is a major bug. Gonna fix this now.

**Comment by Visual1mpact** [comment]
https://github.com/Visual1mpact/Paradox_AntiCheat/commit/650d6454ea17f356c5a56b5473e49fadf84d6596
