### ISSUE TITLE
Can't op myself 

### ISSUE THREAD

**Issue by bluelogy** [Visual1mpact/Paradox_AntiCheat#42]
"You need to be Paradox-Opped to use this command." this shows every time I type !op (password) although I have already sat up the password 
 
![Screenshot_20220701_172802](https://user-images.githubusercontent.com/59976658/176913950-94bdd48d-e52b-4755-8ee0-22d6b05aa597.jpg)

and I did edit the file and followed the steps.

**Comment by Visual1mpact** [comment]
Best I can say is be absolutely sure you are not misspelling the password when typing it in the chat window as it is case sensitive. The smallest typo will fail because it won't return with a match. If you think it is good and are still experiencing issues then my next suggestion would be to reach out to me on Discord and send me your mcpack so I can investigate the issue locally. This will allow me to confirm if it's user error or an actual bug.

**Comment by bluelogy** [comment]
the password is just "test", I typed it correctly

**Comment by bluelogy** [comment]
how do I reach you at discord

**Comment by Visual1mpact** [comment]
There is a link in the readme
